version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: health_insurance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hardhat-node:
    image: node:18-alpine
    working_dir: /app
    command: npx hardhat node --hostname 0.0.0.0
    ports:
      - "8545:8545"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

volumes:
  postgres_data: