# Generated by Django 5.2.6 on 2025-09-30 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wallet_address", models.CharField(max_length=128, unique=True)),
                ("national_id", models.CharField(max_length=128, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="HospitalTxnRecord",
            fields=[
                (
                    "hospitalTransactionId",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("encrypted_transaction_blob", models.TextField(blank=True)),
                ("storacha_cid", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("claim_id", models.CharField(max_length=200, unique=True)),
                ("claim_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "claim_status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="submitted",
                        max_length=50,
                    ),
                ),
                ("claim_description", models.TextField(blank=True)),
                (
                    "hospital_transaction_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.buyer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClaimDoc",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storacha_cid", models.CharField(blank=True, max_length=100)),
                ("encrypted_doc_blob", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="insurance.claim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_number", models.CharField(max_length=100, unique=True)),
                (
                    "monthly_premium",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.buyer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="claim",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="insurance.policy",
            ),
        ),
    ]
