# Generated by Django 4.2.24 on 2025-10-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0002_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="buyer",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buyer",
            name="password",
            field=models.CharField(default="temp_password", max_length=128),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
