# Generated by Django 5.2.6 on 2025-10-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0005_buyer_tracking_fields"),
    ]

    operations = [
        # Skipping AddField operations for accepted_at and verified_at since they already exist in the database
        # migrations.AddField(
        #     model_name="claim",
        #     name="accepted_at",
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name="claim",
        #     name="verified_at",
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name="claim",
            name="claim_status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("verified", "Verified"),
                    ("unverified", "Unverified"),
                    ("accepted", "Accepted"),
                    ("not_approved", "Not Approved"),
                    ("rejected", "Rejected"),
                    ("paid", "Paid"),
                ],
                default="submitted",
                max_length=50,
            ),
        ),
    ]