# Generated by Django 4.2.24 on 2025-10-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_claim_accepted_at_claim_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='storacha_cid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='premium',
            name='storacha_cid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]